---

- name: Create and Launch EC2 jumphost
  ec2_instance:
    key_name: "{{ aws_key_name }}" 
    instance_type: "{{ ec2_instance_type }}" 
    security_group: "{{ public_sg_id }}"
    vpc_subnet_id: "{{ public_subnet_id }}"
    network:
      assign_public_ip: true
    image_id: "{{ aws_ec2_ami }}" 
    wait: yes
    state: present 
    tags:
      Name: "{{ resource_name }}"
      Persistent: no
  register: ec2_result

- name: Wait for SSH
  wait_for:
    host: "{{ item.public_ip_address }}" 
    port: 22
    delay: 10
    timeout: 100
    state: started
  with_items: "{{ ec2_result.instances }}"

- name: Set fact jumphost IP
  set_fact:
    host_ip: "{{ ec2_result.instances[0].public_ip_address }}"

- name: Add jumphost to inventory
  add_host:
    name: "{{ item.public_ip_address }}"
    groups: "aws,{{ item.tags.Name }}"
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "{{ keypair_destination }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  with_items: "{{ ec2_result.instances }}"