---

- name: Create VPC if not existing
  ec2_vpc_net:
    name: "{{ resource_name }}"
    cidr_block: "{{ vpc_cidr_block }}"
    tags:
      Name: "{{ resource_name }}"
    tenancy: default
  register: vpc_result

- name: Gather info on VPC
  ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ resource_name }}"
  register: vpc_result_info

- name: Set VPC ID
  set_fact:
    vpc_id: "{{ vpc_result_info.vpcs[0].id }}"