---
- name: Install basic requirements
  hosts: openshift_perftest

  vars_files:
    - aws_keys.yml
    - ocp_token.yml

  tasks:
    - name: Save AWS credentials
      template:
        src: credentials.j2
        dest: ~/.aws/credentials
        mode: 0400

  roles:
    - role: oasis_roles.ocp_pull_secrets
    - role: alinabuzachis.ocp_cluster_setup
