---

- name: Get EC2 jumphost ID.
  ec2_instance_info:
    filters:
      "tag:Name": "{{ resource_name }}"
      instance-state-name: ["running"]
  register: ec2_info

- name: Delete EC2 instance.
  ec2_instance:
    state: absent
    wait: true
    instance_ids:
      - "{{ ec2_info.instances[0].instance_id }}"
  when: ec2_info.instances