---
plugin: aws_ec2

ansible_user: ubuntu

boto_profile: default

regions:
  - eu-central-1

hostnames:
  - ip-address

filters:
  tag:Name: openshift_perftest

keyed_groups:
  - key: tags.Name
    separator: ''
