---
# defaults file for aws_jumphost_provision

resource_name: openshift_perftest

vpc_cidr_block: "10.0.0.0/16"

vpc_subnets:
  - name: "Public Subnet - Bench"
    cidr: "10.0.0.0/18"
    az: "{{ aws_region }}a"
    privacy: "Public"

  - name: "Private-Subnet-Bench"
    cidr: "10.0.64.0/18"
    az: "{{ aws_region }}a"
    privacy: "Private"

route_tables:
  - name: Public-Subnet-Bench
    dest: 0.0.0.0/0

security_groups:
  - name: Public-Group-Bench
    description: All permissions for everyone
    rules:
      - proto: tcp
        ports: 80
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on port
      - proto: ssh
        ports: 22
        cidr_ip: 0.0.0.0/0
        rule_desc: allow ssh for everyone

keypair_destination: ~/.ssh/key_bench.pub
ec2_jumphost_name: Jump Host
ec2_instance_type: t3.large
